-- Migration script to add fingerprint column to trivia_questions
-- This column will be used for more accurate question deduplication

-- Add fingerprint column if it doesn't exist
ALTER TABLE IF EXISTS public.trivia_questions
ADD COLUMN IF NOT EXISTS fingerprint TEXT;

-- Create an index on the fingerprint column for faster lookups
CREATE INDEX IF NOT EXISTS idx_trivia_fingerprint ON public.trivia_questions (fingerprint);

-- Comment on the column
COMMENT ON COLUMN public.trivia_questions.fingerprint IS 'Normalized fingerprint of question text and tags for deduplication';

-- Generate fingerprints for existing questions
-- This requires a separate process in the application code
-- The existing questions will need to be updated with fingerprints generated by the app 